# Generated by Django 5.2.6 on 2025-10-25 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=100, unique=True)),
                ('fecha_solicitud', models.DateField()),
                ('tipo_requisicion', models.CharField(choices=[('Material', 'Material'), ('Equipo/Instrumento', 'Equipo/Instrumento'), ('Servicio', 'Servicio')], max_length=50)),
                ('justificacion', models.TextField()),
                ('nombre_solicitante', models.CharField(max_length=255)),
                ('fecha_firma_solicitante', models.DateField(blank=True, null=True)),
                ('nombre_autoriza', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_firma_autoriza', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequisicionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida_num', models.PositiveIntegerField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(max_length=50)),
                ('producto', models.TextField()),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requisitions.requisicion')),
            ],
            options={
                'ordering': ['partida_num'],
            },
        ),
    ]
