# Generated by Django 5.2.6 on 2025-10-25 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicion',
            name='fecha_firma_autoriza',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='fecha_firma_solicitante',
        ),
        migrations.RemoveField(
            model_name='requisicion',
            name='nombre_autoriza',
        ),
        migrations.AddField(
            model_name='requisicion',
            name='approved_by_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_manager_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='approved_by_purchasing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_purchasing_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='approver_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='manager_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='purchasing_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING_MANAGER', 'Pendiente Aprobación Jefe'), ('PENDING_PURCHASING', 'Pendiente Aprobación Compras'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], default='PENDING_MANAGER', max_length=20),
        ),
    ]
