# Generated by Django 5.2.6 on 2025-10-11 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnebiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elaborador', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_estudio', models.CharField(blank=True, max_length=255, null=True)),
                ('patrocinador', models.CharField(blank=True, max_length=255, null=True)),
                ('principio_activo', models.TextField(blank=True, null=True)),
                ('condicion', models.CharField(blank=True, max_length=255, null=True)),
                ('orden_servicio', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('clave_asignada', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_proyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('llave_pago_cofepris', models.CharField(blank=True, max_length=255, null=True)),
                ('no_cofepris', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_pago_ip', models.DateField(blank=True, null=True)),
                ('fecha_pago_comite', models.DateField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('historial', models.TextField(blank=True, null=True)),
                ('segmento_contable', models.CharField(blank=True, max_length=255, null=True)),
                ('diseno', models.CharField(blank=True, max_length=255, null=True)),
                ('tamano_muestras', models.CharField(blank=True, max_length=255, null=True)),
                ('datos_adjuntos', models.FileField(blank=True, null=True, upload_to='attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
