# Generated by Django 5.2.6 on 2025-10-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_unebikey_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
