# Generated by Django 5.2.6 on 2025-10-18 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unebikey',
            name='datos_adjuntos',
        ),
    ]
