# Generated by Django 5.2.6 on 2025-10-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_unebikey_datos_adjuntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='unebikey',
            name='fecha_cofepris',
            field=models.DateField(blank=True, null=True),
        ),
    ]
