# Generated by Django 5.2.6 on 2025-10-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnebiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elaborador', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_estudio', models.CharField(blank=True, max_length=255, null=True)),
                ('patrocinador', models.CharField(blank=True, max_length=255, null=True)),
                ('principio_activo', models.TextField(blank=True, null=True)),
                ('condicion', models.CharField(blank=True, max_length=255, null=True)),
                ('orden_servicio', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('fecha_cofepris', models.DateField(blank=True, null=True)),
                ('clave_asignada', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_proyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('llave_pago_cofepris', models.CharField(blank=True, max_length=255, null=True)),
                ('no_cofepris', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_pago_ip', models.DateField(blank=True, null=True)),
                ('fecha_pago_comite', models.DateField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('historial', models.TextField(blank=True, null=True)),
                ('segmento_contable', models.CharField(blank=True, max_length=255, null=True)),
                ('diseno', models.CharField(blank=True, max_length=255, null=True)),
                ('tamano_muestras', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
